services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://${BESZEL_HOST}
    volumes:
      - /opt/docker/appdata/beszel/beszel/beszel_data:/beszel_data
      - /opt/docker/appdata/beszel/beszel/beszel_socket:/beszel_socket
    networks:
      - traefik-net
      - beszel-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.beszel.rule=Host(`${BESZEL_HOST}`)
      - traefik.http.routers.beszel.entrypoints=web,websecure
      - traefik.http.services.beszel.loadbalancer.server.port=8090

      - homepage.group=${GRP_OPS}
      - homepage.name=Beszel
      - homepage.icon=beszel
      - homepage.href=https://${BESZEL_HOST}
      - homepage.siteMonitor=https://${BESZEL_HOST}
      - homepage.description=Lightweight server monitoring hub with historical data, docker stats, and alerts.
      - homepage.widget.type=beszel
      - homepage.widget.url=http://beszel:8090
      - homepage.widget.username=${BESZEL_USERNAME}
      - homepage.widget.password=${BESZEL_PASSWORD}
      - homepage.widget.version=2
      - homepage.widget.systemId=dkh38wvwyquo8ah

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      LISTEN: 45876
      HUB_URL: https://${BESZEL_HOST}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      KEY: ${BESZEL_AGENT_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/appdata/beszel/beszel-agent/beszel_agent_data:/var/lib/beszel-agent

networks:
  traefik-net:
    external: true
  beszel-net:
    external: true