networks:
  traefik-net:
    external: true
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - /opt/docker/appdata/speedtest-tracker/config:/config
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - APP_KEY=${SPEEDTEST_APP_KEY}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.speedtest.rule=Host(`${SPEEDTEST_HOST}`)
      - traefik.http.routers.speedtest.entrypoints=websecure
      - traefik.http.services.speedtest.loadbalancer.server.port=80
