services:
  broker:
    image: redis:8
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - /opt/docker/appdata/paperless/paperless-broker/data:/data
    networks:
      - paperless-net

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    restart: unless-stopped
    depends_on:
      - broker
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: ${PAPERLESS_UID}
      USERMAP_GID: ${PAPERLESS_GID}
      PAPERLESS_TIME_ZONE: ${PAPERLESS_TIME_ZONE}
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE}
      PAPERLESS_OCR_LANGUAGES: ${PAPERLESS_OCR_LANGUAGES}
    volumes:
      - /opt/docker/appdata/paperless/paperless-webserver/data:/usr/src/paperless/data
      - /mnt/usb-hdd/docker/data/paperless:/usr/src/paperless/media
      - /opt/docker/appdata/paperless/paperless-webserver/export:/usr/src/paperless/export
      - /opt/docker/appdata/paperless/paperless-webserver/consume:/usr/src/paperless/consume
    networks:
      - traefik-net
      - paperless-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.paperless.rule=Host(`${PAPERLESS_HOST}`)
      - traefik.http.routers.paperless.entrypoints=web,websecure
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      - homepage.group=${GRP_DOCS}
      - homepage.name=Paperless-ngx
      - homepage.icon=paperless-ngx
      - homepage.href=https://${PAPERLESS_HOST}
      - homepage.siteMonitor=https://${PAPERLESS_HOST}
      - homepage.description=A community-supported supercharged document management system - scan, index and archive all your documents
      - homepage.widget.type=paperlessngx
      - homepage.widget.url=http://webserver:8000
      - homepage.widget.key=${PAPERLESS_API_KEY}

  ai:
    image: clusterzx/paperless-ai
    container_name: paperless-ai
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      PUID: ${PAPERLESS_UID}
      PGID: ${PAPERLESS_GID}
      PAPERLESS_AI_PORT: 3000
      RAG_SERVICE_URL: http://webserver:8000
      RAG_SERVICE_ENABLED: "true"
      PAPERLESS_API_URL: http://webserver:8000/api
      PAPERLESS_URL: http://webserver:8000
      OLLAMA_API_URL: http://ollama:11434
    volumes:
      - /opt/docker/appdata/paperless/paperless-ai/data:/app/data
    networks:
      - traefik-net
      - paperless-net
      - ollama-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.paperless-ai.rule=Host(`${PAPERLESS_AI_HOST}`)
      - traefik.http.routers.paperless-ai.entrypoints=web,websecure
      - traefik.http.services.paperless-ai.loadbalancer.server.port=3000
      
      - homepage.group=${GRP_DOCS}
      - homepage.name=Paperless-ai
      - homepage.icon=paperless-ai
      - homepage.href=https://${PAPERLESS_AI_HOST}
      - homepage.siteMonitor=https://${PAPERLESS_AI_HOST}
      - homepage.description=An automated document analyzer for Paperless-ngx using OpenAI API, Ollama, Deepseek-r1, Azure and all OpenAI API compatible Services to automatically analyze and tag your documents. 

networks:
  traefik-net:
    external: true
  paperless-net:
    external: true
  ollama-net:
    external: true