networks:
  traefik-net:
    external: true
  servarr-net:
    # wegen sonarr -> ntfy notifications
    external: true
services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    init: true
    restart: unless-stopped
    command:
      - serve
      - --cache-file
      - /var/cache/ntfy/cache.db
    env_file:
      - .env
    networks:
      - traefik-net
      - servarr-net
    volumes:
      - /opt/docker/appdata/ntfy/cache:/var/cache/ntfy
      - /opt/docker/appdata/ntfy/server.yml:/etc/ntfy/server.yml:ro
    healthcheck:
      test:
        - CMD-SHELL
        - wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo
          '"healthy"\s*:\s*true' || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      # HTTP
      - traefik.http.routers.ntfy-http.rule=Host(`${NTFY_HOST}`)
      - traefik.http.routers.ntfy-http.entrypoints=web
      # HTTPS
      - traefik.http.routers.ntfy-https.rule=Host(`${NTFY_HOST}`)
      - traefik.http.routers.ntfy-https.entrypoints=websecure
      - traefik.http.routers.ntfy-https.tls=true
      # Service-Port
      - traefik.http.services.ntfy.loadbalancer.server.port=80

      - homepage.group=${GRP_AUT}
      - homepage.name=ntfy
      - homepage.icon=ntfy
      - homepage.href=https://${NTFY_HOST}
      - homepage.description=Send push notifications to your phone or desktop using PUT/POST
      - homepage.siteMonitor=https://${NTFY_HOST}