networks:
  traefik-net:
    external: true

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - /opt/docker/appdata/n8n:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_HOST: ${N8N_HOST}
      N8N_PROTOCOL: https
      N8N_PORT: 5678
      WEBHOOK_TUNNEL_URL: https://${N8N_HOST}/
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${N8N_HOST}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      
      - homepage.group=${GRP_AI}
      - homepage.name=n8n
      - homepage.icon=n8n
      - homepage.href=https://${N8N_HOST}
      - homepage.description=Workflow automation & low-code platform
      - homepage.siteMonitor=https://${N8N_HOST}